# Generated by Django 2.1.15 on 2020-02-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_track_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='user',
        ),
    ]
